version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: script/requirement.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: ubuntu
