# Generated by Django 4.1.5 on 2023-02-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profile", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="Deleted at"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=50)),
                ("hsn_code", models.CharField(max_length=20, null=True)),
                ("description", models.TextField()),
                ("image", models.FileField(null=True, upload_to="IMAGES/PRODUCT")),
                ("reference_number", models.CharField(max_length=30, null=True)),
                ("barcode", models.CharField(max_length=30, unique=True)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.brand",
                    ),
                ),
                (
                    "tax_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.producttaxcategory",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.distributorprofile",
                        to_field="tenant_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="Deleted at"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.product"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.distributorprofile",
                        to_field="tenant_id",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.metricunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="Deleted at"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("current_stock", models.DecimalField(decimal_places=2, max_digits=10)),
                ("minimum_stock", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.product",
                        to_field="barcode",
                    ),
                ),
                (
                    "stock_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="stock.productunit",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.distributorprofile",
                        to_field="tenant_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductUnitConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="Deleted at"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("factor", models.DecimalField(decimal_places=5, max_digits=10)),
                (
                    "from_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_unit",
                        to="stock.productunit",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.distributorprofile",
                        to_field="tenant_id",
                    ),
                ),
                (
                    "to_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_unit",
                        to="stock.productunit",
                    ),
                ),
            ],
            options={"unique_together": {("from_unit", "to_unit")},},
        ),
        migrations.AddIndex(
            model_name="productunit",
            index=models.Index(
                fields=["product"], name="stock_produ_product_70028a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productunit", unique_together={("product", "unit")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["name", "reference_number", "barcode"],
                name="stock_produ_name_18d00b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product", unique_together={("name", "tenant", "brand")},
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["product"], name="stock_inven_product_79c0d3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventory", unique_together={("product", "tenant")},
        ),
    ]
