# Generated by Django 4.1.5 on 2023-02-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_alter_distributorprofile_admin_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="distributorprofile", name="api_user",),
    ]
