# Generated by Django 4.1.5 on 2023-02-26 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_remove_distributorprofile_api_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailerprofile",
            name="admin_user",
            field=models.OneToOneField(
                limit_choices_to={"type": "RETAILER"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
