# Generated by Django 4.1.5 on 2023-03-07 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_alter_retailerprofile_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='id_proof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_id_proof', to='profile.document'),
        ),
    ]
