# Generated by Django 4.1.5 on 2023-03-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_alter_employeeprofile_id_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.businessprofile'),
        ),
    ]
