# Generated by Django 4.1.5 on 2023-02-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="Deleted at"),
                ),
                ("name", models.CharField(max_length=60)),
                ("code", models.CharField(blank=True, max_length=20, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="Deleted at"),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=10)),
                ("logo", models.FileField(null=True, upload_to="IMAGES/LOGO")),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("code", models.CharField(max_length=2, unique=True)),
                ("alpha_three_code", models.CharField(max_length=3, null=True)),
                ("currency_code", models.CharField(max_length=3, unique=True)),
            ],
            options={"verbose_name_plural": "countries",},
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="Deleted at"),
                ),
                ("name", models.CharField(max_length=30)),
                ("has_unique_number", models.BooleanField(default=True)),
                ("has_back_image", models.BooleanField(default=False)),
                ("has_expiry_date", models.BooleanField(default=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="MetricUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="Deleted at"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("weight", "Weight"),
                            ("dimension", "Dimension"),
                            ("count", "Count"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("symbol", models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PackageDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="Deleted at"),
                ),
                ("length", models.PositiveIntegerField(default=1)),
                ("width", models.PositiveIntegerField(default=1)),
                ("height", models.PositiveIntegerField(default=1)),
                ("weight", models.PositiveIntegerField(default=1)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="Deleted at"),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("code", models.CharField(max_length=10)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ProductTaxCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="Deleted at"),
                ),
                ("gst", models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                (
                    "sgst",
                    models.DecimalField(decimal_places=3, default=0, max_digits=5),
                ),
                (
                    "igst",
                    models.DecimalField(decimal_places=3, default=0, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("code", models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="state",
            index=models.Index(
                fields=["name", "code"], name="common_stat_name_3719c5_idx"
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.country"
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.state"
            ),
        ),
        migrations.AddField(
            model_name="producttaxcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.productcategory"
            ),
        ),
        migrations.AddField(
            model_name="producttaxcategory",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.state"
            ),
        ),
        migrations.AddField(
            model_name="packagedimension",
            name="dimension_unit",
            field=models.ForeignKey(
                limit_choices_to={"category": "dimension"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dimension_unit",
                to="common.metricunit",
                to_field="code",
            ),
        ),
        migrations.AddField(
            model_name="packagedimension",
            name="weight_unit",
            field=models.ForeignKey(
                limit_choices_to={"category": "weight"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weight_unit",
                to="common.metricunit",
                to_field="code",
            ),
        ),
        migrations.AddIndex(
            model_name="metricunit",
            index=models.Index(
                fields=["name", "code", "category"], name="common_metr_name_4f51e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(
                fields=["name", "code"], name="common_coun_name_f91867_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(
                fields=["name", "code"], name="common_bran_name_df20b8_idx"
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="common.province"
            ),
        ),
        migrations.AddIndex(
            model_name="province",
            index=models.Index(
                fields=["name", "code"], name="common_prov_name_b07436_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="producttaxcategory", unique_together={("category", "state")},
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["zip_code", "name", "province"],
                name="common_area_zip_cod_89bbcc_idx",
            ),
        ),
    ]
